### ISSUE TITLE
nsb14: slider values exceed max

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#108]
Again one of these sporadic sometimes happening things:
Had a servo motor  connected to a scratch variabble, and to check speed I moved the sliders left right quite fast. The servo followed pretty good, but sometimes the slider has set the value of the variable to 101 (min=0, max=100). Took me prox 20 mins to find a second event like this...

**Comment by timrowledge** [comment]
We can't reproduce, so drop it for now
