### ISSUE TITLE
raspbian, nuscratch integration

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#122]
There are a few integration problems in raspbian.

- scratch script '/usr/bin/scratch' should propagate command line options to squeak
Problem: command line "scratch somescript.sb" does not work.

- when using the call from scratch shellscript "/usr/bin/squeak-stack -vm... --document sample.sb", the script is not found. It is only found when full path /home/pi/sample.sb is given. Relative pathes should work.

- when initially "saving as" a project, the folder "Documents" is offered, although this is not available. When using this, there is a directory error (so folder gets not created)
When save is used, "Documents/Scratch Projects" is offered (but created then when not existing).

**Comment by williamhbell** [comment]
@asb, do you have a feel for when the shell script fix and launcher fix might be in the Raspbian update repo.?  I am running an event next weekend and would like to know what to tell the attendees that might ask this question.

**Comment by asb** [comment]
Apologies for the delay. Now should be fixed.
