### ISSUE TITLE
Cannot input Japanese character

### ISSUE THREAD

**Issue by abee2** [raspberrypi/scratch#125]
We could input Japanese character on previous version by the following method.
https://github.com/naominix/scratchjpime
http://www.asu.ac.jp/hachi/v3/scratch14ime.html
We need to change that method for NuScratch.
One problem is the VM, squeak-stack 4.0-3145 #3, does not support "-compositioninput" option.

**Comment by timrowledge** [comment]
After much work by a bunch of people including Yoshiki & Dave, the VM now accepts the -compositioninput flag. The relevant plugins compile and seem to work ok. 
Not much needed changing in the image, fortunately, but the list of packages to install and stuff to configure is a bit intimidating. We should have a script to cover it sometime soon.

**Comment by timrowledge** [comment]
WE have existence proof of the ability to install the right things and end up with a composition window being used at the right times. Yay.
Now to make a suitable script to automate it all.

**Comment by timrowledge** [comment]
I've been able to build suitable scripts to start Scratch and provide the relevant flags. They seem to work ok on Pi's with direct connected displays BUT I have problems with xrdp requiring use of a sudo wrapper and vnc simply not working with the composition window.

Still need script to do all the install stuff.

**Comment by timrowledge** [comment]
Yoshiki has done tests (by someone that understand Japanese!) and asserts it works. Ready for release
