### ISSUE TITLE
could upgrade to flash version

### ISSUE THREAD

**Issue by penn5** [raspberrypi/scratch#131]
https://github.com/LLK/scratch-flash

**Comment by timrowledge** [comment]
Nope. Flash does not run on Pi. 
There have been some claims of a sort of success by using chrome and its sorta-flash support but this is not an appropriate place to discuss it; try the raspberry.org forums.

And it won't be as fast as Scratch on Cog/Squeak anyway. Nor as supportive of the Pi.

**Comment by penn5** [comment]
ok
