### ISSUE TITLE
exporting background to write protected directory

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#133]
Export a background to a write protected directory gives the following error screen:
![write_protected_dir](https://cloud.githubusercontent.com/assets/5240331/8243093/6b1f6d4c-1614-11e5-8071-a806ce564c32.jpg)
Expected: should give an kid-compatible error message.

**Comment by timrowledge** [comment]
It certainly should!

I'll get back to working on stuff like this soon; currently very busy with making the system a lot faster.

**Comment by heppg** [comment]
Hello Tim,
this ticket is low prio. The 'pangofont'-problem reported earlier is
really high prio, as it does not allow to use text in sprite/backgroud.
Regards,
Gerhard

**Comment by timrowledge** [comment]
I'd like to make it so you can't choose a bad filename but that isn't looking too easy right now.

**Comment by timrowledge** [comment]
I've wrapped the image media exporting in an error handler so at least it will provide a notification rather than crash.
Fixed in NuScratch-tpr.376
