### ISSUE TITLE
scratch-2015-07-18 installation requirements

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#141]
Got a nice popup on a fresh installed raspbian.
![2015-08-01-081318_1824x984_scrot](https://cloud.githubusercontent.com/assets/5240331/9020862/c62842ee-3825-11e5-919a-23ff8b531532.png)
Expected: it should be in the install document what the prereqs are.

**Comment by timrowledge** [comment]
Yes, wiringPi has to be installed; we'll need to get that incorporated into the OS build and the apt-get stuff
