### ISSUE TITLE
scratch-2015-07-18 piglow causes exit

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#142]
pi2
wiringpi installed as described on http://wiringpi.com/download-and-install/
i2c enabled by raspi-config
Started scratch
loaded gpio-PiGlow.sb

result is: scratch exits without notice.
debug log is containing multiple sessions.

Error: External module not found
1 August 2015 8:12:24.597 am

VM: unix - Smalltalk
Image: Squeak4.5 [latest update: #15047]

SecurityManager state:
Restricted: false
FileAccess: true
SocketAccess: true
Working Dir /home/pi/fastScratch
Trusted Dir /home/pi/fastScratch/secure
Untrusted Dir /home/pi/fastScratch/My Squeak

ScratchWiringPiInterface(Object)>>error:
	Receiver: a ScratchWiringPiInterface
	Arguments and temporary variables: 
		t1: 	'External module not found'
	Receiver's instance variables: 
a ScratchWiringPiInterface
ScratchWiringPiInterface(Object)>>externalCallFailed
	Receiver: a ScratchWiringPiInterface
	Arguments and temporary variables: 
		t1: 	15
	Receiver's instance variables: 
a ScratchWiringPiInterface
ScratchWiringPiInterface>>wiringPiSetupGpio
	Receiver: a ScratchWiringPiInterface
	Arguments and temporary variables: 

	Receiver's instance variables: 
a ScratchWiringPiInterface
ScratchWiringPiInterface class>>uniqueInstance
	Receiver: ScratchWiringPiInterface
	Arguments and temporary variables: 
		t1: 	a ScratchWiringPiInterface
	Receiver's instance variables: 
		superclass: 	Object
		methodDict: 	a MethodDictionary(#analogRead:->(ScratchWiringPiInterface>>#analog...etc...
		format: 	0
		instanceVariables: 	nil
		organization: 	('pin handling' analogRead: analogWrite:value: digitalRead: digit...etc...
		subclasses: 	nil
		name: 	#ScratchWiringPiInterface
		classPool: 	a Dictionary(#UniqueInstance->nil )
		sharedPools: 	an OrderedCollection(WiringPiGPIOConstants)
		environment: 	Smalltalk
		category: 	#'Scratch-Plugins'

GPIOAccessorWiringPi>>initialize
	Receiver: a GPIOAccessorWiringPi
	Arguments and temporary variables: 

	Receiver's instance variables: 
		library: 	nil

GPIOAccessorWiringPi class(Behavior)>>new
	Receiver: GPIOAccessorWiringPi
	Arguments and temporary variables: 

	Receiver's instance variables: 
		superclass: 	GPIOAccessor
		methodDict: 	a MethodDictionary(#initialize->(GPIOAccessorWiringPi>>#initialize ...etc...
		format: 	65537
		instanceVariables: 	#('library')
		organization: 	('initialize-release' initialize wiringPiSetupGpio)
('pin read/wr...etc...
		subclasses: 	nil
		name: 	#GPIOAccessorWiringPi
		classPool: 	nil
		sharedPools: 	nil
		environment: 	Smalltalk
		category: 	#'HardwarePeripherals-Core'

ScratchGPIOBasicHandler(ScratchGPIORootHandler)>>initialize
	Receiver: a ScratchGPIOBasicHandler
	Arguments and temporary variables: 

	Receiver's instance variables: 
		broadcastNamesDictionary: 	nil
		sortedBroadcastNames: 	nil
		variableNamesDictionary: 	nil
		sortedVariableNames: 	nil
		stage: 	nil
		server: 	nil
		invertPins: 	false
		gpioAccessor: 	nil
		validPins: 	nil

ScratchGPIOBasicHandler>>initialize
	Receiver: a ScratchGPIOBasicHandler
	Arguments and temporary variables: 

	Receiver's instance variables: 
		broadcastNamesDictionary: 	nil
		sortedBroadcastNames: 	nil
		variableNamesDictionary: 	nil
		sortedVariableNames: 	nil
		stage: 	nil
		server: 	nil
		invertPins: 	false
		gpioAccessor: 	nil
		validPins: 	nil

ScratchGPIOBasicHandler class(Behavior)>>new
	Receiver: ScratchGPIOBasicHandler
	Arguments and temporary variables: 

	Receiver's instance variables: 
		superclass: 	ScratchGPIORootHandler
		methodDict: 	a MethodDictionary(#initialize->(ScratchGPIOBasicHandler>>#initiali...etc...
		format: 	65545
		instanceVariables: 	nil
		organization: 	('initialize-release' initialize)
('variable handling' processAut...etc...
		subclasses: 	nil
		name: 	#ScratchGPIOBasicHandler
		classPool: 	nil
		sharedPools: 	an OrderedCollection(WiringPiGPIOConstants)
		environment: 	Smalltalk
		category: 	#'Scratch-GPIODevices'
		myDeviceName: 	#AbsolutelyNobodyAtAll

ScratchGPIOServer>>initialize
	Receiver: a ScratchGPIOServer
	Arguments and temporary variables: 

	Receiver's instance variables: 
		stage: 	nil
		lastSentValues: 	a Dictionary()
		incomingBroadcasts: 	an OrderedCollection()
		outgoingBroadcasts: 	an OrderedCollection()
		broadcastCache: 	a Set()
		sensorValues: 	a Dictionary()
		addonHandler: 	a ScratchGPIONullHandler
		rootHandler: 	nil

ScratchGPIOServer class(Behavior)>>new
	Receiver: ScratchGPIOServer
	Arguments and temporary variables: 

	Receiver's instance variables: 
		superclass: 	Object
		methodDict: 	a MethodDictionary(#addBroadcastsSeenTo:->(ScratchGPIOServer>>#addB...etc...
		format: 	65544
		instanceVariables: 	#('stage' 'lastSentValues' 'incomingBroadcasts' 'outgoingBro...etc...
		organization: 	('accessing' addBroadcastsSeenTo:)
('private-variables' clearCach...etc...
		subclasses: 	nil
		name: 	#ScratchGPIOServer
		classPool: 	a Dictionary(#AddOn->#AddOn #Debugging->false #Enabled->true #OnByDe...etc...
		sharedPools: 	nil
		environment: 	Smalltalk
		category: 	#'Scratch-Networking'

ScratchStageMorph>>startGpioServer
	Receiver: a ScratchStageMorph(4180445)
	Arguments and temporary variables: 

	Receiver's instance variables: 
		bounds: 	567@71 corner: 1047@431
		owner: 	a ScratchFrameMorph(946053)
		submorphs: 	{a ScratchSpriteMorph(2197771)}
		fullBounds: 	nil
		color: 	Color white
		extension: 	a MorphExtension (1917949) [other:  (dropEnabled -> true) (dragEnabl...etc...
		objName: 	'Stage'
		vars: 	a Dictionary()
		lists: 	a Dictionary()
		blocksBin: 	a ScratchScriptsMorph(1742603)
		isClone: 	false
		media: 	an OrderedCollection(background1 [image] pop [sound])
		costume: 	background1 [image]
		costumeChangeMSecs: 	0
		filterPack: 	nil
		visibility: 	100
		volume: 	100
		tempoBPM: 	60
		sceneStates: 	a Dictionary()
		zoom: 	1.0
		hPan: 	0
		vPan: 	0
		penTrailsForm: 	nil
		lastPenPositions: 	nil
		runningBlocks: 	an OrderedCollection()
		inProcessStep: 	false
		sensorBoard: 	a SensorBoardMorph(3298093)
		midiPortNum: 	-1
		midiPort: 	nil
		notePlayerDict: 	a Dictionary()
		obsoleteSavedState: 	nil
		sprites: 	an OrderedCollection(a ScratchSpriteMorph(2197771))
		scratchServer: 	nil
		isQuarterSize: 	false
		cachedForm: 	nil
		showMotorBlocks: 	false
		cachedBackground: 	nil
		gpioServer: 	nil

ScratchFrameMorph>>startGpioServer
	Receiver: a ScratchFrameMorph(946053)
	Arguments and temporary variables: 

	Receiver's instance variables: 
		bounds: 	0@0 corner: 1057@786
		owner: 	a PasteUpMorph(2434915) [world]
		submorphs: 	{an ImageFrameMorph(4058813) . a ScratchStageMorph(4180445) . a Scra...etc...
		fullBounds: 	nil
		color: 	Color blue
		extension: 	a MorphExtension (309835) [sticky] 
		topPane: 	an ImageFrameMorph(1211553)
		viewerPane: 	a ScratchViewerMorph(929580)
		scriptsPane: 	a ScratchScriptEditorMorph(3292590)
		stageFrame: 	an ImageFrameMorph(3431209)
		workPane: 	a ScratchStageMorph(4180445)
		titlePane: 	an ImageFrameMorph(2048934)
		libraryPane: 	a ScratchLibraryMorph(617570)
		menuPanel: 	a DockingBarMorph(2265581)
		stageButtonsPanel: 	an AlignmentMorph(1728155)
		readoutPane: 	an ImageFrameMorph(4058813)
		logoMorph: 	a SketchMorph(4026713)
		projectTitleMorph: 	a StringMorph(3740189)''
		flagButton: 	a ToggleButton(1322475)
		fillScreenFlag: 	true
		paintingInProgress: 	false
		projectDirectory: 	UnixFileDirectory on '/home/pi/Documents/Scratch Projects'
		projectName: 	''
		projectInfo: 	a Dictionary()
		author: 	''
		loginName: 	''
		loginPassword: 	''
		watcherPositions: 	a Dictionary()
		shuffledCostumeNames: 	nil
		justSaved: 	false
		viewModeButtons: 	an OrderedCollection(a ToggleButton(1220429) a ToggleButton(16...etc...
		viewMode: 	#normal
		lastViewMode: 	nil
		viewModeButtonsPanel: 	an AlignmentMorph(4024701)
		toolbarPanel: 	an AlignmentMorph(1609099)
		lastWeDoPoll: 	229063315

ScratchFrameMorph>>installNewProject:
	Receiver: a ScratchFrameMorph(946053)
	Arguments and temporary variables: 
		t1: 	a ScratchStageMorph(4180445)
		t2: 	a SensorBoardMorph(3298093)
		t3: 	{a ScratchSpriteMorph(2197771)}
	Receiver's instance variables: 
		bounds: 	0@0 corner: 1057@786
		owner: 	a PasteUpMorph(2434915) [world]
		submorphs: 	{an ImageFrameMorph(4058813) . a ScratchStageMorph(4180445) . a Scra...etc...
		fullBounds: 	nil
		color: 	Color blue
		extension: 	a MorphExtension (309835) [sticky] 
		topPane: 	an ImageFrameMorph(1211553)
		viewerPane: 	a ScratchViewerMorph(929580)
		scriptsPane: 	a ScratchScriptEditorMorph(3292590)
		stageFrame: 	an ImageFrameMorph(3431209)
		workPane: 	a ScratchStageMorph(4180445)
		titlePane: 	an ImageFrameMorph(2048934)
		libraryPane: 	a ScratchLibraryMorph(617570)
		menuPanel: 	a DockingBarMorph(2265581)
		stageButtonsPanel: 	an AlignmentMorph(1728155)
		readoutPane: 	an ImageFrameMorph(4058813)
		logoMorph: 	a SketchMorph(4026713)
		projectTitleMorph: 	a StringMorph(3740189)''
		flagButton: 	a ToggleButton(1322475)
		fillScreenFlag: 	true
		paintingInProgress: 	false
		projectDirectory: 	UnixFileDirectory on '/home/pi/Documents/Scratch Projects'
		projectName: 	''
		projectInfo: 	a Dictionary()
		author: 	''
		loginName: 	''
		loginPassword: 	''
		watcherPositions: 	a Dictionary()
		shuffledCostumeNames: 	nil
		justSaved: 	false
		viewModeButtons: 	an OrderedCollection(a ToggleButton(1220429) a ToggleButton(16...etc...
		viewMode: 	#normal
		lastViewMode: 	nil
		viewModeButtonsPanel: 	an AlignmentMorph(4024701)
		toolbarPanel: 	an AlignmentMorph(1609099)
		lastWeDoPoll: 	229063315

ScratchFrameMorph>>newScratchProject
	Receiver: a ScratchFrameMorph(946053)
	Arguments and temporary variables: 
		t1: 	nil
		t2: 	a ScratchStageMorph(4180445)
		t3: 	a ScratchSpriteMorph(2197771)
	Receiver's instance variables: 
		bounds: 	0@0 corner: 1057@786
		owner: 	a PasteUpMorph(2434915) [world]
		submorphs: 	{an ImageFrameMorph(4058813) . a ScratchStageMorph(4180445) . a Scra...etc...
		fullBounds: 	nil
		color: 	Color blue
		extension: 	a MorphExtension (309835) [sticky] 
		topPane: 	an ImageFrameMorph(1211553)
		viewerPane: 	a ScratchViewerMorph(929580)
		scriptsPane: 	a ScratchScriptEditorMorph(3292590)
		stageFrame: 	an ImageFrameMorph(3431209)
		workPane: 	a ScratchStageMorph(4180445)
		titlePane: 	an ImageFrameMorph(2048934)
		libraryPane: 	a ScratchLibraryMorph(617570)
		menuPanel: 	a DockingBarMorph(2265581)
		stageButtonsPanel: 	an AlignmentMorph(1728155)
		readoutPane: 	an ImageFrameMorph(4058813)
		logoMorph: 	a SketchMorph(4026713)
		projectTitleMorph: 	a StringMorph(3740189)''
		flagButton: 	a ToggleButton(1322475)
		fillScreenFlag: 	true
		paintingInProgress: 	false
		projectDirectory: 	UnixFileDirectory on '/home/pi/Documents/Scratch Projects'
		projectName: 	''
		projectInfo: 	a Dictionary()
		author: 	''
		loginName: 	''
		loginPassword: 	''
		watcherPositions: 	a Dictionary()
		shuffledCostumeNames: 	nil
		justSaved: 	false
		viewModeButtons: 	an OrderedCollection(a ToggleButton(1220429) a ToggleButton(16...etc...
		viewMode: 	#normal
		lastViewMode: 	nil
		viewModeButtonsPanel: 	an AlignmentMorph(4024701)
		toolbarPanel: 	an AlignmentMorph(1609099)
		lastWeDoPoll: 	229063315

ScratchFrameMorph>>startup
	Receiver: a ScratchFrameMorph(946053)
	Arguments and temporary variables: 
		t1: 	an OrderedCollection()
		t2: 	nil
		t3: 	nil
		t4: 	11
	Receiver's instance variables: 
		bounds: 	0@0 corner: 1057@786
		owner: 	a PasteUpMorph(2434915) [world]
		submorphs: 	{an ImageFrameMorph(4058813) . a ScratchStageMorph(4180445) . a Scra...etc...
		fullBounds: 	nil
		color: 	Color blue
		extension: 	a MorphExtension (309835) [sticky] 
		topPane: 	an ImageFrameMorph(1211553)
		viewerPane: 	a ScratchViewerMorph(929580)
		scriptsPane: 	a ScratchScriptEditorMorph(3292590)
		stageFrame: 	an ImageFrameMorph(3431209)
		workPane: 	a ScratchStageMorph(4180445)
		titlePane: 	an ImageFrameMorph(2048934)
		libraryPane: 	a ScratchLibraryMorph(617570)
		menuPanel: 	a DockingBarMorph(2265581)
		stageButtonsPanel: 	an AlignmentMorph(1728155)
		readoutPane: 	an ImageFrameMorph(4058813)
		logoMorph: 	a SketchMorph(4026713)
		projectTitleMorph: 	a StringMorph(3740189)''
		flagButton: 	a ToggleButton(1322475)
		fillScreenFlag: 	true
		paintingInProgress: 	false
		projectDirectory: 	UnixFileDirectory on '/home/pi/Documents/Scratch Projects'
		projectName: 	''
		projectInfo: 	a Dictionary()
		author: 	''
		loginName: 	''
		loginPassword: 	''
		watcherPositions: 	a Dictionary()
		shuffledCostumeNames: 	nil
		justSaved: 	false
		viewModeButtons: 	an OrderedCollection(a ToggleButton(1220429) a ToggleButton(16...etc...
		viewMode: 	#normal
		lastViewMode: 	nil
		viewModeButtonsPanel: 	an AlignmentMorph(4024701)
		toolbarPanel: 	an AlignmentMorph(1609099)
		lastWeDoPoll: 	229063315

ScratchFrameMorph>>saveImageForEndUser
	Receiver: a ScratchFrameMorph(946053)
	Arguments and temporary variables: 

	Receiver's instance variables: 
		bounds: 	0@0 corner: 1056@786
		owner: 	a PasteUpMorph(2434915) [world]
		submorphs: 	{an ImageFrameMorph(4058813) . a ScratchStageMorph(4180445) . a Scra...etc...
		fullBounds: 	0@0 corner: 1056@829
		color: 	Color blue
		extension: 	a MorphExtension (309835) [sticky] 
		topPane: 	an ImageFrameMorph(1211553)
		viewerPane: 	a ScratchViewerMorph(929580)
		scriptsPane: 	a ScratchScriptEditorMorph(3292590)
		stageFrame: 	an ImageFrameMorph(3431209)
		workPane: 	a ScratchStageMorph(4180445)
		titlePane: 	an ImageFrameMorph(2048934)
		libraryPane: 	a ScratchLibraryMorph(617570)
		menuPanel: 	a DockingBarMorph(2265581)
		stageButtonsPanel: 	an AlignmentMorph(1728155)
		readoutPane: 	an ImageFrameMorph(4058813)
		logoMorph: 	a SketchMorph(4026713)
		projectTitleMorph: 	a StringMorph(3740189)''
		flagButton: 	a ToggleButton(1322475)
		fillScreenFlag: 	true
		paintingInProgress: 	false
		projectDirectory: 	UnixFileDirectory on '/home/pi/Documents/Scratch Projects'
		projectName: 	''
		projectInfo: 	a Dictionary()
		author: 	''
		loginName: 	''
		loginPassword: 	''
		watcherPositions: 	a Dictionary()
		shuffledCostumeNames: 	nil
		justSaved: 	false
		viewModeButtons: 	an OrderedCollection(a ToggleButton(1220429) a ToggleButton(16...etc...
		viewMode: 	#normal
		lastViewMode: 	nil
		viewModeButtonsPanel: 	an AlignmentMorph(4024701)
		toolbarPanel: 	an AlignmentMorph(1609099)
		lastWeDoPoll: 	229063315

[] in MenuItemMorph>>invokeWithEvent:
	Receiver: a MenuItemMorph(1028720)'save image for end-user'
	Arguments and temporary variables: 
<<error during printing>
	Receiver's instance variables: 
		bounds: 	44@48 corner: 180@63
		owner: 	a ScratchMenuMorph(2198810)
		submorphs: 	#()
		fullBounds: 	44@48 corner: 180@63
		color: 	Color black
		extension: 	a MorphExtension (3243019) [other:  (layoutProperties -> a LayoutPro...etc...
		font: 	a StrikeFont(Verdana13 15)
		emphasis: 	0
		contents: 	'save image for end-user'
		hasFocus: 	false
		isEnabled: 	true
		subMenu: 	nil
		isSelected: 	false
		target: 	a ScratchFrameMorph(946053)
		selector: 	#saveImageForEndUser
		arguments: 	#()
		icon: 	nil
		lastMousePosition: 	nil

BlockClosure>>ensure:
	Receiver: [closure] in MenuItemMorph>>invokeWithEvent:
	Arguments and temporary variables: 
		t1: 	[closure] in CursorWithMask(Cursor)>>showWhile:
		t2: 	nil
		t3: 	nil
	Receiver's instance variables: 
		outerContext: 	MenuItemMorph>>invokeWithEvent:
		startpc: 	152
		numArgs: 	0

--- The full stack ---
ScratchWiringPiInterface(Object)>>error:
ScratchWiringPiInterface(Object)>>externalCallFailed
ScratchWiringPiInterface>>wiringPiSetupGpio
ScratchWiringPiInterface class>>uniqueInstance
GPIOAccessorWiringPi>>initialize
GPIOAccessorWiringPi class(Behavior)>>new
ScratchGPIOBasicHandler(ScratchGPIORootHandler)>>initialize
ScratchGPIOBasicHandler>>initialize
ScratchGPIOBasicHandler class(Behavior)>>new
ScratchGPIOServer>>initialize
ScratchGPIOServer class(Behavior)>>new
ScratchStageMorph>>startGpioServer
ScratchFrameMorph>>startGpioServer
ScratchFrameMorph>>installNewProject:
ScratchFrameMorph>>newScratchProject
ScratchFrameMorph>>startup
ScratchFrameMorph>>saveImageForEndUser
[] in MenuItemMorph>>invokeWithEvent:
BlockClosure>>ensure:
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
CursorWithMask(Cursor)>>showWhile:
MenuItemMorph>>invokeWithEvent:
MenuItemMorph>>mouseUp:
MenuItemMorph>>handleMouseUp:
MouseButtonEvent>>sentTo:
MenuItemMorph(Morph)>>handleEvent:
MorphicEventDispatcher>>dispatchDefault:with:
MorphicEventDispatcher>>dispatchEvent:with:
MenuItemMorph(Morph)>>processEvent:using:
MorphicEventDispatcher>>dispatchDefault:with:
MorphicEventDispatcher>>dispatchEvent:with:
ScratchMenuMorph(Morph)>>processEvent:using:
ScratchMenuMorph(Morph)>>processEvent:
ScratchMenuMorph(MenuMorph)>>handleFocusEvent:
[] in HandMorph>>sendFocusEvent:to:clear:
BlockClosure>>on:do:
PasteUpMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
HandMorph>>processEvents
[] in WorldState>>doOneCycleNowFor:
Array(SequenceableCollection)>>do:
WorldState>>handsDo:
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:
PasteUpMorph>>doOneCycle
[] in MorphicProject>>spawnNewProcess
[] in BlockClosure>>newProcess

**Comment by timrowledge** [comment]
This is actually a 'feature' of wiringPi that needs to be changed; if you try to connect again to someinth that is already setup it dumps the process instead of returning an error. Not really a good idea.

**Comment by timrowledge** [comment]
I've added some code in the initialisation of i2c devices that *might* reduce this issue's impact.It's in the November 15 release candidate so let's see what happens.

**Comment by timrowledge** [comment]
see also #183

**Comment by timrowledge** [comment]
Closed along with #183
