### ISSUE TITLE
scratch-2015-07-18 piface support

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#143]
The input values from 23s17 are not read back. 
input8 seems to be tied to output0. The other inputs do not show any action.
Naming of inputs is input_1..8, but should be input_0..7

in piface, there are pullups on the 23s17-inputs, Port B, so default values are '1'. When the buttons are pressed, it is getting '0'.

**Comment by timrowledge** [comment]
Added pull ups and reading of the output pin state

**Comment by timrowledge** [comment]
Fixed in Scratch-tpr.293
