### ISSUE TITLE
scratch-11092015, pwm not working

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#146]
setting an output to pwm, there is no pwm signal output. From gpio18pwm0 to gpio18pwm1024 there is no pulse output. When I try to set this gpio to high or low, this works. So at least I connected my scope to the correct pin.

**Comment by timrowledge** [comment]
Ah, yes. A interesting screw-up in parsing; at one point I was allowing high/on/1 & off/low/0 and thus by parsing for any of those before checking for a 'pwm' you can end up missing the pwm completely. Fixed for the upcoming release.
