### ISSUE TITLE
jessie initial release opens libreoffice to handle scratch help html files

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#149]
The 'help' menu button opens libreoffice in edit mode for the html help pages.

Expected: should be opened in browser.

**Comment by timrowledge** [comment]
Ah, this old problem returns; for some time it would open the very old web-browser. We use the unix 'xdg-open' (or something like that) api to ask the system to handle an html file and it does whatever it thinks best. I guess it isn't making a very good choice right now...

**Comment by timrowledge** [comment]
Simon - another one I think you need to know about; looks like some config doohickey that xdg-open looks at is mixed up?

**Comment by spl237** [comment]
xdg-open just calls the system file manager, so it is the file associations in pcmanfm that need to be fixed - libreoffice seems to grab a lot of them when it is installed. The easy fix is to open the File Manager, navigate to a .html file (such as /usr/share/scratch/Help/index.html), right-click and choose Epiphany to open it, ticking the box for "always use this application to open files of this type". That creates the required association. 

We'll look at including a predefined association with .html files in the next release.

**Comment by timrowledge** [comment]
Seems to have been solved for the november release at least.
