### ISSUE TITLE
fontscale property not working

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#176]
in .scratch.ini, a property
fontscale = 1.5
does not have any (at least no visible) effect.
Other values as 0.2 or 2.5 also.

scratch is 2015-11-11

**Comment by timrowledge** [comment]
Ah. Well that's embarrassing; I actually added that the day *after* the 2015-11-11 version was released to the foundation, so it doesn't actually exist for people to use. Next time..

**Comment by timrowledge** [comment]
Actually fixed for january release.
