### ISSUE TITLE
turn into new sprite: use very deep copy

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#179]
In backgrounds, when using function from context menu 'turn into new sprite', works perfect when background is not having text. When text is included, there is an error message 'use very deep copy'.
The result is fine, text is available in sprite as an object.

Problem: error message is not helpful.

**Comment by timrowledge** [comment]
Ouch; sorry about that. Looks like I'm still using some old and deprecated code in there. I didn't even know you could turn a background into a new sprite...

**Comment by heppg** [comment]
Didn't know either, but tried to reproduce some bugs from school. Kids
found that their sprites with text with 'umlaut' aka utf chars have been
displayed wrong. Did not find a path to this char error, but found this
one instead.

**Comment by timrowledge** [comment]
As ought to have been obvious to me, the same issue exists when turning sprite costumes into new sprites. Happily, that means the fix solves both cases :-)
We simply need to actually use a #veryDeepCopy to copy the media item. Fixed ready for next release.

**Comment by timrowledge** [comment]
Fixed in Scratch-tpr.323
