### ISSUE TITLE
Sprite scaling appears to ignore set centre point

### ISSUE THREAD

**Issue by timrowledge** [raspberrypi/scratch#184]
In NuScratch we appear to be ignoring the user set centre point of a sprite when scaling. See https://www.raspberrypi.org/forums/viewtopic.php?f=77&t=142467&p=942412&sid=8cb57658e351592369d161258d1ad2b0#p942412 for explanation and the forum-attached sb file for a nice demonstration.

**Comment by timrowledge** [comment]
Ah, the WarpBlt>rotate... method has changed between 1997 & 2015. I'll have to work out how the centre position calculation has altered.

**Comment by timrowledge** [comment]
After much distraction and confusion I finally got to look into this. The solution is decently simple - actually pay attention to the scaling factor within the calculation of the resized/rotated bitmap!
Fixed in Graphics-tpr.342 & Scratch-tpr.344 ready for next release.

**Comment by seanmcmanus** [comment]
Thanks for fixing this, Tim!
