### ISSUE TITLE
No LICENSE-file in this repo

### ISSUE THREAD

**Issue by mobluse** [raspberrypi/scratch#185]
There is no LICENSE-file in this repo. Is this intentional? What is the license?

**Comment by timrowledge** [comment]
Sorry, you've lost me already. What repo?

**Comment by mobluse** [comment]
This repository: https://github.com/raspberrypi/scratch/
If this is an open source project it should have a license, such as GPL, MIT etc.

**Comment by cymplecy** [comment]
The code (although based on open source) has been closed off

**Comment by timrowledge** [comment]
That would be incorrect.

This is not a code repository but rather a place to stick artefacts to share in order to avoid trying to email giant files.

**Comment by tobiasbp** [comment]
I too assumed the source for Scratch was available here. I see that it is not. I wonder why the source is not available? What is the license of the original code? Are there links that would be informative in this regard?

I have been evangelizing to my Scratch(On Pi)-using student about the wonders of open source under the wrong assumption that Scratch on Pi was open source. Ouch..

**Comment by timrowledge** [comment]
See, the fact that you would assume that the source code would be here is an immediate indication that you don't understand Smalltalk. Aside from the prosaic fact that the code isn't in a state where I would wish to inflict it upon the outside world, Smalltalk is shared with Monticello packages kept in a suitable repository such as SqueakSource. Smalltalk is a live system, not a dead text in mundane ascii code files.

So no, the code is not 'closed off'. This is not a repository where the code would go. It does not, therefore, lack a license file. It is just a place where some bits get transferred and bug reports are collated.
