### ISSUE TITLE
Scratch doesn't recognise different instruments

### ISSUE THREAD

**Issue by seanmcmanus** [raspberrypi/scratch#186]
Scratch on the Raspberry Pi doesn't appear to play the different instruments. There are some small differences in note duration when different instruments are used, I think, but the tones sound alike.

I know this has been an issue for some time but I couldn't see it here so I've added it.

**Comment by timrowledge** [comment]
I guess you're referring to the MIDI instruments in the 'play drum' and 'set instrument to' blocks, yes?
If so you need to do a quick install to load the MIDI sound libraries that provide the actual sounds - it was concluded that the fairly large library wasn't a sensible thing to include in the default Raspbian package.
The script you need to run is /usr/share/scratch/timidityinstall.sh - it doesn't seem to need 'sudo'. Do please add a comment her if it causes problems - and especially if it works ok! Outside confirmation is always good to see.

**Comment by seanmcmanus** [comment]
Thank you, Tim! I didn't know that, but running that script has set it all up for me and the music works fine now. I ran the script with sudo (didn't read your note carefully enough) so I don't know if it works without, but it works fine with it.

**Comment by abee2** [comment]
@timrowledge If possible, could you please refer to the contribution of this function? https://www.raspberrypi.org/forums/viewtopic.php?f=77&t=88024&p=825177

**Comment by timrowledge** [comment]
Hi Kazuhiro - I'm not sure what you are asking for here. I hope we've properly credited the original authors but if we haven't, tell me where you'd like it improved.

Oddly enough I was about to contact you to ask if anyone knows why the timidity service seems to keep taking more and more cpu time until it gets to 100%. I think it's a recent change but I can't be sure. It might be a bug in timidity, or perhaps we're not handling the MIDI stuff quite right in NuScratch.
