### ISSUE TITLE
Some missing translation entries

### ISSUE THREAD

**Issue by abee2** [raspberrypi/scratch#189]
I found some missing translation entries on PO files of 2016-01-15 version.

msgid "Start GPIO server"
msgid "Stop GPIO server"
msgid "edit"

I added them to ja.po and ja_HIRA.po and translated them in Japanese.
http://squeakland.jp/abee/tmp/ja_po_20160424.zip
I hope that the next release will merge with them.

**Comment by timrowledge** [comment]
Thanks again - these should make it to the next release ok.

**Comment by timrowledge** [comment]
Files moved into place ready

**Comment by abee2** [comment]
@timrowledge Thank you for your quick response.
