### ISSUE TITLE
Instructions error in Examples

### ISSUE THREAD

**Issue by DarrenTownsend** [raspberrypi/scratch#227]
In the two ultrasonic examples, the wiring instructions say to connect Trig to gpio26 and Echo to gpio16, but these are reversed in the scripts.

**Comment by timrowledge** [comment]
Damn! All hail Tpyos, Queen of spling misteaks.

Well spotted. I didn't think anyone ever read my notes...

**Comment by DarrenTownsend** [comment]
I've been away from it for a while (THB partly due to our discussion regarding servos), but having another look now I've started an after-school club. I may actually propose some additions & edits to the docs, once I figure out how GitHub works!

**Comment by timrowledge** [comment]
If the revised project files are small enough to just email, feel free to send them to tim at rowledge dot org

**Comment by DarrenTownsend** [comment]
Will do, Tim.

**Comment by timrowledge** [comment]
OK, I've fixed the files at my end; happily the Fritzing graphic I did was already correct.
It'll go out in the next update.
