### ISSUE TITLE
nuscratch8, sporadic exits

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#37]
In some situations, sporadic, not well reproduceable, the programs exits.
'Exit' means: window closed, process is away, no error popups, no dialogs or alike.
Found this when create variable (global), create same name again (local), you get a dialog: variable already exists, when pressing ok then scratch exits.
Had this also on startup, when remote sensor network is enabled, you get a dialog like 'sensor network enabled', when pressing ok then scratch dies.
This is happening not each time. Looked for logfiles or dumps, but could not find any.

**Comment by heppg** [comment]
Hello, unfortunately I see this happen still in current 2015-jan-15. It seems to happen when remote sensor network gets connected or is disconnecting. Kids in school just notice 'its away', and I tell them to save frequent. But it is annoying. I see it there two, three times in a session with 7 workplaces.
Tried to reproduce, but after clicking some hours and stopping/startung scratchClient, everything worked ok. 
Is there a possibility to enable dump output for squeak, or collect debug/trace in another way ?

**Comment by timrowledge** [comment]
Well I guess there has to be a way to enable saving a core dump; presumably some setting somewhere. If squeak crashes and knows about it (as opposed to whoosh! abort!) it tries to write a SqueakDebug.log file to the default directory. Normally that is the directory the image file lives in, which probably isn't all that useful for a production Scratch since most users won't be aware of where that might be.

**Comment by heppg** [comment]
Hello, the computers in school are not internet connected, but I have a
DHCP/switch assembly in place to enable debug access to the systems when
needed. So I could do some data collection in the background.

Possibly there are some error conditions. When socket connection is
established and data are send too fast in whatever direction. Or when
scratchClient is disconnecting while some not complete record remains in
buffer.

**Comment by heppg** [comment]
Hello, made some analysis to find out whether my scratchClient software is causing trouble. So I wrote a simplified code, which sometimes sends wrong length (huge records) information toward scratch. Scratch reports an exception, and then a 'close to near memory limit', but does not exit. Good.

**Comment by heppg** [comment]
Still trying to reproduce this. Found a strange sequence. iValue is a sensor variable. This variable is running from 
cd ~/scratchClient
python src/scratchClient.py -c test
and increments every second.

Start scratch
Create a script for cat, just one operator:
 mod ( iValue, 100)

Duplicate sprite 
In first sprite, duplicate the mod-operator with rightclick mouse, duplicate and drop this into the second sprite in object palette. And its away.

Tried multiple, each time scratch exit.

**Comment by timrowledge** [comment]
I strongly suspect this is related to the alsa sound system. It completely improperly sets the sigio handler to SIG_DFL after playing a sound and any socket activity after that raises a sigio which then terminates the process! Insanity!

We have now got a decent fix working its way to Raspbian and maybe even all the way up to alsa project.

**Comment by heppg** [comment]
Hello, good news.
I remember that I had exits also in early times of testing this now not
so new release, when no sound was involved. Although I do not know
whether some sort of feedback clicks are around I never heard nor noticed.
Regards,
Gerhard

**Comment by timrowledge** [comment]
No new reports so we'll hope the problem was indeed ALSA and the COGVM changes a lot of stuff as well. Close in hopefulness.
