### ISSUE TITLE
nsb12, test 240; drag on small size stage: sprite gets full size during dragging

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#90]
drag sprite on stage
drag on small size stage
sprite gets full size during dragging

**Comment by timrowledge** [comment]
related rather strongly to #47

**Comment by timrowledge** [comment]
Fixed by the new scaled stage wrapper code. Works very nicely now, and handles odd scalings too so there is some future option to use 1.5 or 3 etc for different size screens.
